# Taken from roblox-ts under the MIT license https://github.com/roblox-ts/roblox-ts/blob/master/.github/workflows/ci.yml
# Taken also from Ukendio's game repo under the MPL-2.0 license https://github.com/Ukendio/Game/blob/master/.github/workflows/test.yml

name: Test

on:
    workflow_dispatch:
    schedule:
        - cron: "0 7 * * *"
    pull_request:
    push:
      branches:
        - master

jobs:
    test:
        name: Unit Tests
        runs-on: windows-latest
        timeout-minutes: 10
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2.3.4

            - name: Install Roblox Studio
              uses: OrbitalOwen/roblox-win-installer-action@1.1
              with:
                  cookie: ${{ secrets.ROBLOSECURITY || '_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_C69CD347CB94D4B570DAC174E5F0D2216899B2649D76CE38DB16EF47B85A15527138A2F6AF1A6C4DE4E935C4F9EDEC94567D6E65097CFBCA28294E4BEC2CDFDDC367FDA3A7720B64AFDCDF96C38A40C411A7682C252B0BE949281CC20B546E8949DDB95EE562B69CA3D18CDE5AECC4D67AC2BC2DE56758F45F0C2101213461045B82A829B13810B4A134759941FBC5AB850FB1367BACA384D11E80D39E390E6F20C390B58F7A3B3B991BA8DAF42279CD7F0F113E02302D5C8D6FE706423B6A94263A228570A67D10DF018797C018646FB9915EB7A779E64A8589582F1241374672C50D934AE32D7087C00A27CD9AE0914B4F7F5493655E64B1A2D8B6151C5D135FB0670F79350F70A60AE04B25A49EA0DE6292F4A8A75C34020864B5096B5774FD3FC33BAD7C5FC01707DF0BCA5EA3AD9E1476D3EE012AC036FF87AF9AEC58F6DD9F81C1E64B450FA890B780000C699683097134' }}
                  token: ${{ secrets.MEMO_ACCESS_TOKEN }}

            - name: Install Foreman
              uses: rojo-rbx/setup-foreman@v1.0.1
              with:
                  token: ${{ secrets.MEMO_ACCESS_TOKEN }}

            - name: Install NPM dependencies
              uses: bahmutov/npm-install@v1.7.4

            # I used the dev version of roblox-ts, don't judge me :D
            - name: Install roblox-ts
              run: npm i -g roblox-ts@next

            - name: Compile and run tests
              run: npm run test
