# Taken from roblox-ts under the MIT license https://github.com/roblox-ts/roblox-ts/blob/master/.github/workflows/ci.yml
# Taken also from Ukendio's game repo under the MPL-2.0 license https://github.com/Ukendio/Game/blob/master/.github/workflows/test.yml

name: Test

on:
    workflow_dispatch:
    schedule:
        - cron: "0 7 * * *"
    pull_request:
    push:

jobs:
    test:
        name: Unit Tests
        runs-on: windows-latest
        timeout-minutes: 10
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2.3.4

            - name: Install Roblox Studio
              uses: OrbitalOwen/roblox-win-installer-action@1.1
              with:
                  cookie: ${{ secrets.ROBLOSECURITY }}
                  token: ${{ secrets.MEMO_ACCESS_TOKEN }}

            - name: Install Foreman
              uses: rojo-rbx/setup-foreman@v1.0.1
              with:
                  token: ${{ secrets.MEMO_ACCESS_TOKEN }}

            - name: Install NPM dependencies
              uses: bahmutov/npm-install@v1.7.4

            - name: Compile and run tests
              run: npm run test
